trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: GoTool@0
  displayName: Go Tools
  inputs:
    version: '1.16'

- task: Go@0
  displayName: Run Tests
  inputs:
    command: 'test'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: Go@0
  displayName: Build Go Project
  inputs:
    command: 'build'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: Docker@2
  inputs:
    containerRegistry: 'service-connection-cr'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'